org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_id=ftblibrary
readable_name=FTB Library
mod_version=8
mod_author=FTB Team

# Maven
archives_base_name=ftb-library
maven_group=dev.ftb.mods

# MC
minecraft_version=26.2
supported_minecraft_versions=26.2,26.2.1,26.2.2
minecraft_version_range_maven=[26.2,27)
minecraft_version_range_semver=>=26.2.0

# Deps
neoforge_version=26.2.0.7-beta
neoforge_version_range=[26.2.0.7-beta,27)
neoforge_loader_version=4

fabric_loader_version=0.19.3
fabric_api_version=0.154.2+26.2
fabric_api_version_range=>=0.144.0+26.2

jei_version=30.2.0.18

json5_version=3.0.0
amecs_key_modifiers_version=mc26.2.0:1.0.2
amecs_key_bundle_version=mc26.2.0:1.6.5

modmenu_version=20.0.1

curseforge_id_forge=404465
curseforge_id_fabric=438495
