org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod
mod_id=ftblibrary
readable_name=FTB Library
mod_version=5
mod_author=FTB Team

# Maven
archives_base_name=ftb-library
maven_group=dev.ftb.mods

# MC
minecraft_version=26.2-pre-1
supported_minecraft_versions=26.2
minecraft_version_range_maven=[26.1,27)
minecraft_version_range_semver=>=26.1.0

# Deps
neoforge_version=26.1.2.7-beta
neoforge_version_range=[26.1.0.0-beta,27)
neoforge_loader_version=4

fabric_loader_version=0.19.2
fabric_api_version=0.149.2+26.2
fabric_api_version_range=>=0.149.1+26.1.2

jei_version=29.5.0.26

json5_version=3.0.0
amecs_key_modifiers_version=mc26.1.0:1.0.2
amecs_key_bundle_version=mc26.1.0:1.6.5

modmenu_version=18.0.0-alpha.8

curseforge_id_forge=404465
curseforge_id_fabric=438495
