pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url "https://maven.ftb.dev/releases/" }
        maven { url "https://maven.architectury.dev/" }
        maven { url "https://maven.creeperhost.net/" }
    }
}

include "common", "fabric", "neoforge" // , "forge"

rootProject.name = 'FTB-Library-1.21'
