modLoader = "javafml"
loaderVersion = "[${neoforgeloaderversion},)"
issueTrackerURL = "https://go.ftb.team/support-mod-issues"
license = "All Rights Reserved"

[[mixins]]
config = "ftblibrary-common.mixins.json"

[[mods]]
modId = "ftblibrary"
version = "${version}"
displayName = "FTB Library"
authors = "FTB Team"
description = '''
FTB Library adds nothing.
'''

[[dependencies.ftblibrary]]
modId = "neoforge"
type = "required"
versionRange = "${neoforgeversionrange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftblibrary]]
modId = "minecraft"
type = "required"
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftblibrary]]
modId = "architectury"
type = "required"
versionRange = "[${archversion},)"
ordering = "AFTER"
side = "BOTH"
