name: Java CI - Build Release

on:
  release:
    types: [ published ]

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: FTBTeam/mods-meta/.github/workflows/standard-release.yml@main
    with:
      curse-publish-task: curseforge
    secrets:
      ftb-maven-token: ${{ secrets.FTB_MAVEN_TOKEN }}
      saps-token: ${{ secrets.SAPS_TOKEN }}
      curse-token: ${{ secrets.CURSEFORGE_KEY }}